/*
 * HPCM cmdb REST API Documentation
 *
 * HPE Performance Cluster Manager 'cmdb' service features a REST API. This section describes its implementation.  Standard REST API concepts (such as HTTP verbs, return codes, JSON, etc.) are not covered here.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package hpcm_client

type NetworkSettings struct {
	Name           string `json:"name,omitempty"`
	DefaultGateway string `json:"defaultGateway,omitempty"`
	Nics           []Nic  `json:"nics,omitempty"`
	IpAddress      string `json:"ipAddress,omitempty"`
	MacAddress     string `json:"macAddress,omitempty"`
	SubnetMask     string `json:"subnetMask,omitempty"`
	MgmtServerIp   string `json:"mgmtServerIp,omitempty"`
}
