/*
 * HPCM cmdb REST API Documentation
 *
 * HPE Performance Cluster Manager 'cmdb' service features a REST API. This section describes its implementation.  Standard REST API concepts (such as HTTP verbs, return codes, JSON, etc.) are not covered here.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package hpcm_client

import (
	"time"
)

type Node struct {
	Name                 string              `json:"name,omitempty"`
	Aliases              map[string]string   `json:"aliases,omitempty"`
	Id                   int64               `json:"id,omitempty"`
	Uuid                 string              `json:"uuid,omitempty"`
	Etag                 string              `json:"etag,omitempty"`
	CreationTime         time.Time           `json:"creationTime,omitempty"`
	ModificationTime     time.Time           `json:"modificationTime,omitempty"`
	DeletionTime         time.Time           `json:"deletionTime,omitempty"`
	Links                map[string]string   `json:"links,omitempty"`
	Network              *NetworkSettings    `json:"network,omitempty"`
	Image                *ImageSettings      `json:"image,omitempty"`
	Platform             *PlatformSettings   `json:"platform,omitempty"`
	Management           *ManagementSettings `json:"management,omitempty"`
	Controller           *ControllerSettings `json:"controller,omitempty"`
	Location             *LocationSettings   `json:"location,omitempty"`
	InternalName         string              `json:"internalName,omitempty"`
	Type_                string              `json:"type,omitempty"`
	ImageTransport       string              `json:"imageTransport,omitempty"`
	ImagePending         bool                `json:"imagePending,omitempty"`
	TemplateName         string              `json:"templateName,omitempty"`
	RootFs               string              `json:"rootFs,omitempty"`
	OperationalStatus    int32               `json:"operationalStatus,omitempty"`
	AdministrativeStatus int32               `json:"administrativeStatus,omitempty"`
	Managed              bool                `json:"managed,omitempty"`
	Monitoring           string              `json:"monitoring,omitempty"`
	RootSlot             int32               `json:"rootSlot,omitempty"`
	BiosBootMode         string              `json:"biosBootMode,omitempty"`
	BootOrder            int32               `json:"bootOrder,omitempty"`
	IscsiRoot            string              `json:"iscsiRoot,omitempty"`
	Inventory            *interface{}        `json:"inventory,omitempty"`
	// Write-only field to configure the controller this node is attached to at creation time
	NodeController string                 `json:"nodeController,omitempty"`
	Attributes     map[string]interface{} `json:"attributes,omitempty"`
}
