name: Promote build to a release (stable)
on:
  push:
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]+'
      - 'v?[0-9]+.[0-9]+.[0-9]+.post[0-9]+'
  workflow_dispatch:
env:
  STREAM: stable
jobs:
  Promote:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Jfrog setup
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: https://artifactory.algol60.net
          JF_USER: ${{ secrets.ARTIFACTORY_ALGOL60_USERNAME }}
          JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ALGOL60_TOKEN }}

      - uses: ./.github/actions/prepare-artifacts
        with:
          STREAM: ${{ env.STREAM }}

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true # if the job is re-ran to catch missed artifacts, allow updates
          generateReleaseNotes: true
          artifacts: ${{ env.DIR_UPLOAD }}/*
          prerelease: false
          makeLatest: true

  generate_publish_docs:
    name: generate docs and publish with mike
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Also fetch git-tags

    - uses: actions/setup-go@v4
      with:
        go-version: '1.20' # The Go version to download (if necessary) and use.
    
    # generate updated docs from any changes made to cani codebase
    - run: go run main.go makedocs

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: configure git user for bot commits
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

    - name: install requirements with nox
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
      
    - name: deploy docs with mike 🚀 and set as latest
      run: |
        mike deploy -F mkdocs.yml -b gh-pages --push --update-aliases ${{ github.ref_name}} latest
        mike set-default -F mkdocs.yml -b gh-pages --push latest

    - name: list doc versions 🚀
      run: |
        mike list -F mkdocs.yml -b gh-pages
